### ISSUE TITLE
Could you please release the paper?

### ISSUE THREAD

**Issue by geekyutao** [EmeryLau/mesa#1]
Hi, I'm very interested with MESA. But I'm still confused about some details. Could you please release the paper? Thanks!

**Comment by EmeryLau** [comment]
Hi, we have submitted the paper to arXiv and it should be available online in a few days. Please note that this repository will be moved to https://github.com/ZhiningLiu1998/mesa. Please check the new repository for the latest information about MESA. Thanks for your interest in our project!
